packages:
  - '.'

allowBuilds:
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true

minimumReleaseAge: 4320

# trustPolicy: no-downgrade

overrides:
  postcss@<8.5.18: "~8.5.23"
  sharp@<0.35.0: "^0.35.0"
  nanoid: "^3.3.17"
