packages:
  - '.'

allowBuilds:
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true

minimumReleaseAge: 4320

# trustPolicy: no-downgrade

overrides:
  postcss: "^8.5.26"
  sharp: "^0.35.3"
  nanoid: "^6.0.1"
