import type { ModelConfig } from '@/types/configurator';

/**
 * Cabinet-1 Model Configuration (Large Variant)
 *
 * Configuration for the duplicated cabinet 3D model (large size variant).
 *
 * Model: cabinets-1.glb (generated via merge_cabinets_simple.js)
 * Structure:
 * - Cabinet_m_cabinet_0: Main cabinet body
 * - Door_Closed_Left_m_cabinet_0: Left door (closed state)
 * - Door_Closed_Right_m_cabinet_0: Right door (closed state)
 * - Door_Left_m_cabinet_0: Left door (open state)
 * - Door_Right_m_cabinet_0: Right door (open state)
 *
 * IMPORTANT: This model was generated by duplicating cabinet.glb.
 * The merge script strips all textures to prevent WebGL binding issues.
 * This causes a visual difference: cabinet.glb has textures, cabinets-1.glb does not.
 * Users will see textured → non-textured transition when switching from small to large.
 *
 * Alternative approaches:
 * - Use Blender to merge models while preserving materials/textures
 * - Modify merge script to preserve textures with proper UV offset handling
 * - Use separate source models designed for each variant
 */
export const CABINET_1_CONFIG: ModelConfig = {
  id: 'cabinet-v2',
  name: 'Large Bar Cabinet (Medium Variant)',
  modelPath: '/cabinet.glb', // Same model as small variant

  // Same parts structure as small cabinet
  parts: [
    {
      nodeName: 'Cabinet_m_cabinet_0',
      materialName: 'm_cabinet',
      displayName: 'Cabinet Body',
      defaultColor: '#ffffffff', // Darker brown to differentiate from small variant (#8B4513)
    },
  ],

  // Interactive parts - same door structure as small cabinet
  interactiveParts: [
    // Left door - closed mesh (visible when door is closed)
    {
      nodeName: 'Door_Closed_Left_m_cabinet_0',
      materialName: 'm_cabinet',
      displayName: 'Left Door Closed',
      stateKey: 'leftDoor',
      group: 'doors',
      defaultState: false, // Start closed
      visibleWhenActive: false, // Show when state is false (closed)
    },
    // Left door - open mesh (visible when door is open)
    {
      nodeName: 'Door_Left_m_cabinet_0',
      materialName: 'm_cabinet',
      displayName: 'Left Door Open',
      stateKey: 'leftDoor',
      group: 'doors',
      defaultState: false, // Start closed
      visibleWhenActive: true, // Show when state is true (open)
    },
    // Right door - closed mesh (visible when door is closed)
    {
      nodeName: 'Door_Closed_Right_m_cabinet_0',
      materialName: 'm_cabinet',
      displayName: 'Right Door Closed',
      stateKey: 'rightDoor',
      group: 'doors',
      defaultState: false, // Start closed
      visibleWhenActive: false, // Show when state is false (closed)
    },
    // Right door - open mesh (visible when door is open)
    {
      nodeName: 'Door_Right_m_cabinet_0',
      materialName: 'm_cabinet',
      displayName: 'Right Door Open',
      stateKey: 'rightDoor',
      group: 'doors',
      defaultState: false, // Start closed
      visibleWhenActive: true, // Show when state is true (open)
    },
  ],

  // Slightly larger scale to visually differentiate from small variant (0.012)
  scale: 0.015,

  // Same positioning as small cabinet
  position: [0, 0, -2.73],

  // Positioning behavior: keep back face pinned to wall
  positioning: {
    type: 'wall-pinned' as const,
    wallOffset: 0,
  },

  camera: {
    position: [-5, 0, 11],
    fov: 17,
  },

  animations: {
    enableRotation: false,
    enableBobbing: false,
  },

  // Dimension constraints for medium/large cabinet variant
  dimensions: {
    length: {
      min: 35,
      max: 60,
      default: 45,
      step: 5,
    },
    width: {
      min: 181, // Starts where small variant ends (width threshold)
      max: 220,
      default: 200,
      step: 10,
    },
    height: {
      min: 200,
      max: 280,
      default: 220,
      step: 10,
    },
  },

  metadata: {
    description:
      'Medium/large bar cabinet variant - same model as small but with larger scale and darker color for visual differentiation.',
    tags: ['furniture', 'cabinet', 'storage', 'medium', 'large'],
    version: '1.0.0',
  },
};
